version: '3.8'

services:
  postgres:
    image: postgres:14.6-bullseye
    container_name: tw_postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

volumes:
  postgres:
    name: tw_postgres
